export const meta = {
  title: "Case Studies",
  announcement: {
    pill: "Case Studies",
    text: "20+ documented engagements for Kotak, JPMorgan, Tekion, Verizon, CARS24, and enterprise clients worldwide.",
    linkHref: "contact",
    linkText: "Start your project →",
  },
  bodyClass: "",
};

export const html =
  '<section class="page-hero bg-theme bg-casestudies">\n  <div class="page-hero-inner">\n    <div class="page-breadcrumb"><a href="/">Home</a><span>/</span><span>Case Studies</span></div>\n    <h1>Real clients.<br><em>Real outcomes.</em></h1>\n    <p class="page-hero-lead">From loan collection systems at Kotak Mahindra Bank to cloud-native DMS at Tekion and AI legal research at LegalDST - explore how we deliver measurable results across industries.</p>\n  </div>\n</section>\n\n<section class="section bg-light" id="casestudies">\n  <div class="wrap">\n    <div class="cs-head">\n      <div>\n        <div class="s-eyebrow">Case Studies</div>\n        <h2 class="s-title">Real clients.<br>Real outcomes.</h2>\n      </div>\n      <div class="cs-filter-wrap" id="csFilters">\n        <button class="cs-f on" data-f="all">All</button>\n        <button class="cs-f" data-f="BFSI">BFSI</button>\n        <button class="cs-f" data-f="Telecom">Telecom</button>\n        <button class="cs-f" data-f="Automotive">Automotive</button>\n        <button class="cs-f" data-f="Healthcare">Healthcare</button>\n        <button class="cs-f" data-f="Insurance">Insurance</button>\n        <button class="cs-f" data-f="Manufacturing">Manufacturing</button>\n        <button class="cs-f" data-f="Retail & E-com">Retail</button>\n        <button class="cs-f" data-f="AI">AI</button>\n      </div>\n    </div>\n    <div class="cs-grid" id="csGrid"></div>\n    <div class="cs-more-wrap"><button class="btn-more" id="csMore">Load More Case Studies &rarr;</button></div>\n  </div>\n</section>\n\n<div class="modal-bd" id="mBd">\n  <div class="modal">\n    <div class="modal-hd">\n      <button class="modal-x" id="mX">&times;</button>\n      <div class="m-ind" id="mInd"></div>\n      <div class="m-cli" id="mCli"></div>\n      <div class="m-proj" id="mProj"></div>\n      <div class="m-tags" id="mTags"></div>\n    </div>\n    <div class="modal-body">\n      <div class="m-sec" data-k="problem"><div class="m-head">The Challenge</div><p class="m-txt" id="mProb"></p></div>\n      <div class="m-sec" data-k="solution"><div class="m-head">Our Solution</div><p class="m-txt" id="mSol"></p></div>\n      <div class="m-sec" data-k="outcomes"><div class="m-head">Outcomes Delivered</div><div class="m-outcomes" id="mOut"></div></div>\n      <div class="m-sec" data-k="tech"><div class="m-head">Technology Stack</div><div class="m-tech-row" id="mTech"></div></div>\n    </div>\n  </div>\n</div>';
